# This is the Discovr Tutorial Shiny App
#
# The main features are uploading the dataset, and graphicly choose for the options
# The output will be the R syntax to reproduce that and the output generated by the Discovr Package

library(shiny)
library(data.table)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Discovr Shiny App"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
       sliderInput("bins",
                   "Number of bins:",
                   min = 1,
                   max = 50,
                   value = 30)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
       plotOutput("distPlot")
    )
  )
))
